# EXPENSIVE: Discogs->Discogs arbitrage (vinili alto valore, notte 00-05)
WATCHLIST_EXPENSIVE = [
    {"name": "Blue Note Jazz",          "query": "blue note jazz original vinyl"},
    {"name": "Prestige Jazz",           "query": "prestige jazz original pressing vinyl"},
    {"name": "Impulse Jazz",            "query": "impulse jazz original vinyl"},
    {"name": "Riverside Jazz",          "query": "riverside jazz vinyl original"},
    {"name": "Verve Jazz",              "query": "verve records jazz original pressing"},
    {"name": "Atlantic Jazz",           "query": "atlantic records jazz original vinyl"},
    {"name": "Northern Soul 45",        "query": "northern soul original 45 rpm rare"},
    {"name": "Krautrock Original",      "query": "krautrock german original vinyl"},
    {"name": "Psych Garage 60s",        "query": "psychedelic garage original vinyl"},
    {"name": "UK Psych",                "query": "uk psychedelic original pressing"},
    {"name": "Library Music",           "query": "library music vinyl rare"},
    {"name": "Test Pressing",           "query": "test pressing vinyl rare"},
    {"name": "Japan OBI Jazz",          "query": "japan obi jazz vinyl"},
    {"name": "Japan OBI Rock",          "query": "japan obi rock vinyl original"},
    {"name": "Folk Psych",              "query": "folk psych original vinyl"},
    {"name": "Reggae Dub Jamaica",      "query": "reggae dub jamaica original vinyl"},
    {"name": "Hip Hop 88-93",           "query": "hip hop original pressing vinyl"},
    {"name": "Funk Soul Original",      "query": "funk soul original pressing vinyl"},
    {"name": "Electronic Ambient",      "query": "electronic ambient original vinyl"},
    {"name": "White Label Promo",       "query": "white label promo vinyl"},
    {"name": "Post Punk Original",      "query": "post punk original pressing vinyl"},
    {"name": "Prog Rock 70s",           "query": "progressive rock original vinyl"},
    {"name": "Bossa Nova Latin",        "query": "bossa nova latin original vinyl"},
    {"name": "Jazz Fusion",             "query": "jazz fusion original pressing vinyl"},
    {"name": "Colored Vinyl Limited",   "query": "colored vinyl limited original rare"},
]

# MIDVALUE: eBay->Discogs arbitrage (vinili medio valore, giorno 06-23)
WATCHLIST_MIDVALUE = [
    {"name": "Pink Floyd",              "query": "pink floyd original vinyl",       "artist": "Pink Floyd"},
    {"name": "Led Zeppelin",            "query": "led zeppelin original vinyl",     "artist": "Led Zeppelin"},
    {"name": "Rolling Stones",          "query": "rolling stones original vinyl",   "artist": "Rolling Stones"},
    {"name": "David Bowie",             "query": "david bowie original vinyl",      "artist": "David Bowie"},
    {"name": "The Beatles",             "query": "beatles original uk vinyl",       "artist": "Beatles"},
    {"name": "Nirvana",                 "query": "nirvana original pressing vinyl", "artist": "Nirvana"},
    {"name": "Radiohead",               "query": "radiohead original vinyl",        "artist": "Radiohead"},
    {"name": "Oasis",                   "query": "oasis original pressing vinyl",   "artist": "Oasis"},
    {"name": "Daft Punk",               "query": "daft punk original vinyl",        "artist": "Daft Punk"},
    {"name": "Aphex Twin",              "query": "aphex twin vinyl",                "artist": "Aphex Twin"},
    {"name": "Boards of Canada",        "query": "boards of canada vinyl",          "artist": "Boards of Canada"},
    {"name": "Kendrick Lamar",          "query": "kendrick lamar vinyl",            "artist": "Kendrick Lamar"},
    {"name": "Frank Ocean",             "query": "frank ocean vinyl",               "artist": "Frank Ocean"},
    {"name": "Mac Miller",              "query": "mac miller vinyl",                "artist": "Mac Miller"},
    {"name": "Tyler The Creator",       "query": "tyler the creator vinyl",         "artist": "Tyler The Creator"},
    {"name": "Madlib",                  "query": "madlib vinyl original",           "artist": "Madlib"},
    {"name": "Flying Lotus",            "query": "flying lotus vinyl",              "artist": "Flying Lotus"},
    {"name": "Pearl Jam",               "query": "pearl jam original vinyl",        "artist": "Pearl Jam"},
    {"name": "Soundgarden",             "query": "soundgarden original vinyl",      "artist": "Soundgarden"},
    {"name": "Pixies",                  "query": "pixies original vinyl",           "artist": "Pixies"},
    {"name": "Smashing Pumpkins",       "query": "smashing pumpkins vinyl",         "artist": "Smashing Pumpkins"},
    {"name": "Tom Waits",               "query": "tom waits vinyl original",        "artist": "Tom Waits"},
    {"name": "Nick Cave",               "query": "nick cave vinyl original",        "artist": "Nick Cave"},
    {"name": "Joy Division",            "query": "joy division original vinyl",     "artist": "Joy Division"},
    {"name": "The Clash",               "query": "the clash original vinyl",        "artist": "The Clash"},
    {"name": "The Cure",                "query": "the cure original vinyl",         "artist": "The Cure"},
    {"name": "New Order",               "query": "new order vinyl original",        "artist": "New Order"},
    {"name": "Miles Davis",             "query": "miles davis vinyl original",      "artist": "Miles Davis"},
    {"name": "John Coltrane",           "query": "john coltrane vinyl original",    "artist": "John Coltrane"},
    {"name": "Record Store Day",        "query": "record store day vinyl limited",  "artist": ""},
]

RARITY_KEYWORDS = [
    "first press","first pressing","1st press","original press","original pressing",
    "original uk","original us","original german","original japan",
    "obi strip","obi-strip","obi","promo","white label promo","not for sale",
    "test press","test pressing","acetate","numbered","hand numbered",
    "limited edition","limited to","colored vinyl","colour vinyl","red vinyl",
    "blue vinyl","white vinyl","clear vinyl","splatter","marbled","picture disc",
    "sealed","still sealed","factory sealed","unplayed","misprint","mispress",
    "alternate cover","withdrawn","banned","gatefold original","matrix","dead wax",
]

RED_FLAGS = [
    "music on vinyl","back to black","vinyl me please","rhino records",
    "demon records","culture factory","wax love","speakers corner",
    "reissue","re-issue","repress","re-press","remastered",
    "digitally remastered","from digital source","180g reissue",
    "anniversary edition","lacquer cut from digital",
]

COUNTRY_VALUE_MULTIPLIERS = {
    "Japan": 1.50, "UK": 1.30, "Germany": 1.20,
    "Netherlands": 1.10, "France": 1.05, "US": 1.00,
    "Italy": 0.90, "Australia": 0.85, "Canada": 0.90, "Spain": 0.80,
}
